name: Close stale PRs

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-pr-stale: 7
          days-before-pr-close: 7
          stale-pr-message: 'This PR is stale because it has been open for 7 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-pr-message: 'This PR was closed because it has been inactive for 7 days since being marked as stale.'
          stale-pr-label: 'stale'
          days-before-issue-stale: -1
          days-before-issue-close: -1
          exempt-pr-labels: 'keep-open,work-in-progress,blocked'
          exempt-draft-pr: false
          exempt-all-pr-assignees: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
